snd-soc-simple-card-objs	:= simple-card.o

obj-$(CONFIG_SND_SIMPLE_CARD)	+= snd-soc-simple-card.o

snd-soc-simple-card-plus-objs	:= simple-card-plus.o

obj-$(CONFIG_SND_SIMPLE_CARD_PLUS)		+= snd-soc-simple-card-plus.o
